version: '3.8'

services:
  tdo-ng-client:
    container_name: todo-ng-client
    build:
      context: ./
      dockerfile: Client.Dockerfile
    depends_on:
      - todo-ng-api
    ports:
      - 4200:80
    networks:
      - todo-ng
  todo-ng-api:
    container_name: todo-ng-api
    build:
      context: ./
      dockerfile: Server.Dockerfile
    ports:
      - 3000:3000
    networks:
      - todo-ng

networks:
  todo-ng:
    name: tng_network